ForntEnd/FrontEnd.Web/FrontEnd.Web/Controllers/CheckOutController.cs
using Dapper;
using FrontEnd.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace FrontEnd.Web.Controllers
{
    public class CheckOutController : Controller
    {
        private IConfiguration Configuration;
        IDatabaseConnectionFactory _db;
        private readonly ILogger<CheckOutController> _logger; private string _apiKey = "";
        public CheckOutController(ILogger<CheckOutController> logger, IConfiguration _configuration, IDatabaseConnectionFactory _database)
        {
            _logger = logger;
            Configuration = _configuration;
            _db = _database;
        }
        private List<InvoiceData> _listInvoice(string customer)
        {
            using var conn = _db.CreateConnectionAsync().Result;
            var query = @$"Select * from tran_Invoice WHERE   CustomerNo = '{customer}' AND (IsActive = 1) AND (IsPaid = 0) Order BY Id DESC";
            var _inv = conn.Query<InvoiceData>(query).ToList();
            return _inv;
        }
        private InvoiceData _getInvoice(long Id)
        {
            using var conn = _db.CreateConnectionAsync().Result;
            var query = @"Select * from tran_Invoice WHERE (Id = @Id) AND  (IsActive = 1) AND (IsPaid = 0)";
            var _inv = conn.Query<InvoiceData>(query, new { Id }).FirstOrDefault();
            return _inv;
        }
        private bool _paidInvoice(string inv_no)
        {
            using var conn = _db.CreateConnectionAsync().Result;
            var query = @"select * from  tran_Invoice  where InvoiceNo = @inv_no AND IsActive = 1 AND IsPaid = 0";
            var _inv = conn.Query<InvoiceData>(query, new { inv_no }).FirstOrDefault();
            if (_inv == null)
            {
                return false;
            }
            else
            {
                //paid
                var insertQuery = @"update tran_Invoice set IsPaid = 1 where InvoiceNo = @inv_no";
                conn.Execute(insertQuery, new { inv_no = inv_no });
                return true;
            }
        }

        private List<InvoiceData> _searching(string custNo)
        {
            var _data = _listInvoice(custNo);
            return _data;
        }
        public IActionResult Index(string customer)
        {
            if (!string.IsNullOrWhiteSpace(customer))
            {
                var model = _listInvoice(customer);

                if (model.Count() > 0)
                {

                ViewBag.AppTitle = "Invoice";
                return View(model);
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            else
            {
                return RedirectToAction("Error");
            }
            
        }
        public IActionResult Error()
        {

            return View();
        }
        public IActionResult Review(long? id)
        {
            var model = _getInvoice(id.Value);
            ViewBag.AppTitle = "Invoice Detail";
            return View(model);
        }
     
        [HttpPost]
        public IActionResult ProcessCheckOut(string mid, string cardid, string token, decimal local_amount, string local_tel, string local_invoice, string local_custno, string local_custname, string local_email, string objectId, string dcc_currency)
        {
            _apiKey = Configuration.GetValue<string>("BaseData:SECKEY");
            var rec = new ReceiveTransactionData()
            {
                mid = mid,
                cardid = cardid,
                secretKey = _apiKey,
                token = token,

                amount = local_amount,
                 email = local_email,
                 tel = local_tel,
                 cust_name = local_custname,
                 cust_no = local_custno,
                 invoice_no = local_invoice,
                 dcc_cur = dcc_currency
            };
            return View(rec);
        }

        [HttpPost]
        public async Task<IActionResult> ProcessCharge(string model, string secret)
        {
            string _apiUrl = Configuration.GetValue<string>("BaseData:APIUrl");
            List<ChargeTransactionData> modeldata = JsonConvert.DeserializeObject<List<ChargeTransactionData>>(model);
            ReponseMessage result = new ReponseMessage();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(modeldata[0]), Encoding.UTF8, "application/json");
                httpClient.DefaultRequestHeaders.Add("x-api-key", secret);

                using (var response = await httpClient.PostAsync(_apiUrl + "card/v2/charge", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    result = JsonConvert.DeserializeObject<ReponseMessage>(apiResponse);
                }
            }

            if (result.@object.Equals("error"))
            {
                return Json(new { status = "error", model = result  });
            }
            else
            {
                return Json(new { status = "success", model = result });
            }

            
        }

        public IActionResult ProcessResult(string ret, decimal AMT, string chg_id)
        {
            if (string.IsNullOrWhiteSpace(chg_id))
            {
                ViewBag.AppTitle = "Result";
                ViewBag.R = ret;
                ViewBag.AMT = AMT;

                return View();
            }
            else
            {
                var _model = SearchChrgeID(chg_id).Result;
                if (_model.@object != "error")
                {
                    if (_model.transaction_state == "Authorized")
                    {
                        //paid
                        bool _paid = _paidInvoice(_model.ref_1);
                        if (_paid)
                        {
                            ViewBag.AppTitle = "Result";
                            ViewBag.R = "Y";
                            ViewBag.AMT = _model.amount;
                            ViewBag.CUS = _model.ref_2;
                            return View();
                        }
                        else
                        {
                            goto onError;
                        }
                    }
                }
                else
                {
                    goto onError;
                }

            onError:
                ViewBag.AppTitle = "Result";
                ViewBag.R = "ไม่สามารถค้นหา Invoice No ได้";
                ViewBag.AMT = _model.amount;
                return View();
            }
        }

        [HttpPost]
        public virtual ActionResult Searching(string customer_no)
        {
            try
            {
                var result = _searching(customer_no);
                try
                {
                    if (result.Count() > 0)
                    {
                        return Json(new { status = "success", message = customer_no });
                    }
                    else
                    {
                        return Json(new { status = "error", message = "ไม่พบข้อมูลลูกค้า .. โปรดตรวจสอบอีกครั้ง" });
                    }
                }
                catch
                {
                    return Json(new { status = "error", message = "ข้อมูลไม่ถูกต้อง โปรดตรวจสอบอีกครั้ง !" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { status = "error", message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<ReponseInquiryMessage> SearchChrgeID(string chr_id)
        {
            _apiKey = Configuration.GetValue<string>("BaseData:SECKEY");
            string _apiUrl = Configuration.GetValue<string>("BaseData:APIUrl");
            ReponseInquiryMessage result = new ReponseInquiryMessage();
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("x-api-key", _apiKey);
                using (var response = await httpClient.GetAsync(_apiUrl + "card/v2/charge/" + chr_id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    result = JsonConvert.DeserializeObject<ReponseInquiryMessage>(apiResponse);
                }
            }
            return result;
        }
    }
}

ForntEnd/FrontEnd.Web/FrontEnd.Web/Views/CheckOut/Index.cshtml
@model List<InvoiceData>
@{
    ViewData["AppTitle"] = "Pay Online";
}
<style>
    .pay-button {
        width: 100% !important;
    }
</style>
<div class="content-body">
    <!-- Bootstrap pricing -->
    <section id="social-cards-bgcolor">
        <div class="row mt-2">
            @foreach (var item in Model)
            {
                <div class="col-xl-4 col-md-6 col-12">
                    <div class="card profile-card-with-cover">
                        <div class="card-content card-deck text-center">
                            <div class="card box-shadow">
                                <div class="card-header bg-info">
                                    <h3 class="my-0 font-weight-bold text-white">INV-@item.InvoiceNo </h3>
                                </div>
                                <div class="card-body">
                                    <h1 class="pricing-card-title">@item.InvoiceAmount.ToString("#,0.00")<small class="text-muted"></small></h1>
                                    <ul class="list-unstyled mt-2 mb-2">
                                        <li><span class="font-weight-bold font-small-2">Customer : </span><span class="font-small-2">(@item.CustomerNo) @item.CustomerName</span></li>
                                    </ul>
                                    <a asp-action="Review" asp-controller="CheckOut" asp-route-id="@item.Id" class="btn btn-block btn-info  btn-glow text-white">แสดงข้อมูล</a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>

    <div class="modal fade text-left" id="PayOnline" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" style="display: none;" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel1">ดำเนินการชำระ - <span id="invNo" class="text-bold-700"></span></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-7">
                            <dl class="row">
                                <dt class="col-sm-5 text-right">รหัสลูกค้า :</dt>
                                <dd class="col-sm-7"><span id="custNo" class="text-bold-700"></span></dd>
                            </dl>
                            <dl class="row">
                                <dt class="col-sm-5 text-right">ชื่อลูกค้า :</dt>
                                <dd class="col-sm-7"><span id="custName" class="text-bold-700"></span></dd>
                            </dl>
                            <dl class="row">
                                <dt class="col-sm-5 text-right">โทรศัพท์ :</dt>
                                <dd class="col-sm-7"><span id="tel" class="text-bold-700"></span></dd>
                            </dl>
                            <dl class="row">
                                <dt class="col-sm-5 text-right">อีเมล์ :</dt>
                                <dd class="col-sm-7"><span id="email" class="text-bold-700"></span></dd>
                            </dl>
                        </div>
                        <div class="col-5 text-center pt-3">
                            <h3 class="pricing-card-title">ยอดชำระ </h3>
                            <h1 class="pricing-card-title"><span class="text-bold-900 text-success" id="invAmt"></span> </h1>
                        </div>
                    </div>
                    
                    <hr>
                    <form method="POST" action="CheckOut/ProcessCheckOut" id="checkout-form">
                        <input type="hidden" id="local_amount" name="local_amount" value="" />
                        <input type="hidden" id="local_invoice" name="local_invoice" value="" />
                        <input type="hidden" id="local_custno" name="local_custno" value="" />
                        <input type="hidden" id="local_custname" name="local_custname" value="" />
                        <input type="hidden" id="local_tel" name="local_tel" value="" />
                        <input type="hidden" id="local_email" name="local_email" value="" />
                        <script type="text/javascript" id="formPay"
                                src="https://dev-kpaymentgateway.kasikornbank.com/ui/v2/kpayment.min.js"
                                data-apikey="pkey_test_20972KOPdDuJNWfBcdgwrRo0TvPwKWt54HM3p"
                                data-amount="1.00"
                                data-currency="CCY"
                                data-payment-methods="card"
                                data-name="ILINK"
                                data-mid="451005210623001">
                        </script>
                    </form>
                </div>                
            </div>
        </div>
    </div>

    <!-- // Bootstrap pricing section end -->
    
</div>

@section Scripts {

    <script>
    function goCheckOut(param) {
        window.location = "/Home/CheckOut";

        //$('#checkout-form').submit();
    }
    $(function () {
        $(".pay-button").addClass("btn btn-lg btn-block btn-info  btn-glow text-white");
    });

        function goPay(custNo, custName, InvNo, InvAmount, tel, email) {
            $("#invNo").html(InvNo); $("#custNo").html(custNo); $("#custName").html(custName); $("#tel").html(tel); $("#email").html(email); $("#invAmt").html(InvAmount);
            $("#local_invoice").val(InvNo); $("#local_custno").val(custNo); $("#local_custname").val(custName); $("#local_amount").val(InvAmount);
            $("#local_tel").val(tel); $("#local_email").val(email);

            $("#formPay").data("data-amount", InvAmount);
            $("#PayOnline").modal("show");
        }

    </script>

}

ForntEnd/FrontEnd.Web/FrontEnd.Web/Views/CheckOut/ProcessCheckOut.cshtml
@model ReceiveTransactionData
    <!-- Bootstrap Checkout form -->
    <section id="social-cards">

        <div class="row mt-2">
            <div class="col-md-4 order-md-2">
                <h4 class="d-flex justify-content-between align-items-center">
                    <span class="text-muted">Your cart</span>
                    @*<span class="badge badge-danger badge-pill">3</span>*@
                </h4>
                <ul class="list-group mb-3 card">

                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total Payment (THB)</span>
                        <strong>  <input type="text" class="form-control" asp-for="amount" disabled></strong>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Currency To Pay</span>
                        <strong>  <input type="text" class="form-control" asp-for="dcc_cur" disabled></strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-8 order-md-1">
                <h4>Check Out Information</h4>
                <form class="needs-validation p-2 bg-white card" novalidate="">
                    <input type="hidden" class="form-control" asp-for="mid">
                    <input type="hidden" class="form-control" asp-for="token">
                    <input type="hidden" class="form-control" asp-for="secretKey">
                    <input type="hidden" class="form-control" asp-for="cardid">
                    <input type="hidden" class="form-control" asp-for="invoice_no">
                    <input type="hidden" class="form-control" asp-for="dcc_cur">

                    <div class="mb-3">
                        <label for="address2">Reference 1 เลขที่ใบแจ้งหนี้ (สามารถแก้ไขได้)<span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" value="@Model.invoice_no" id="ref_1">
                    </div>
                    <div class="mb-3">
                        <label for="address2">Reference 2 รหัสลูกค้า (สามารถแก้ไขได้) <span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" id="ref_2" value="@Model.cust_no">
                    </div>

                    <div class="mb-3">
                        <label for="address2">Decsription<span class="text-muted">(Optional)</span></label>
                        <input type="text" class="form-control" id="description">
                    </div>
                    <button class="btn btn-danger btn-lg btn-block" type="button" onclick="goCharge()">Cofirm Checkout ยืนยันการจ่ายชำระ</button>
                </form>
            </div>
        </div>
    </section>
    <!-- // Bootstrap Checkout form end -->
@section Scripts {

    <script>
        function goCharge() {
            //window.location = "/Home/CheckOut";
            debugger
            var _model = [];
            _model.push({
                token: $("#token").val(),
                amount: $("#amount").val(),
                currency: "THB",
                dcc_data: {
                    dcc_currency: $("#dcc_cur").val()
                },
                additional_data: {
                    mid: $("#mid").val()
                },
                source_type: "card",
                mode: "token",
                ref_1: $("#ref_1").val(),
                ref_2: $("#ref_2").val(),
                reference_order: $("#invoice_no").val() + "_" + Math.floor(Math.random() * 500000).toString(),
                description: $("#description").val()
            });

            $.ajax({
                cache: false,
                async: true,
                type: "POST",
                url: "@Url.Action("ProcessCharge", "CheckOut")",
                data: { model: JSON.stringify(_model), secret: $("#secretKey").val() },
                success: function (data) {
                    if (data.status == "success") {
                        debugger
                        window.location = data.model.redirect_url;
                    } else {
                        //debugger
                        window.location = "/CheckOut/ProcessResult?ret=" + data.model.message + "&AMT=" + $("#amount").val();
                        //toastr.error(data.model.mess);
                    }
                },
                error: function (err) {
                     toastr.error("");
                },
                complete: function (data) {

                }

            });

            //$('#checkout-form').submit();
        }
        $(function () {

        });
    </script>

}

ForntEnd/FrontEnd.Web/FrontEnd.Web/Views/CheckOut/ProcessResult.cshtml
@{ 
    decimal _amt = ViewBag.AMT;
    string _cus = ViewBag.CUS;
}
<div class="content-body">
    <section id="icon-section-bg-gradient">
        <div class="row">
            @if (ViewBag.R == "Y")
            {
                <div class="col-8 mx-auto">
                    <div class="card">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="p-2 bg-gradient-x-success text-white media-body text-left rounded-left">
                                    <h5 class="text-white">ชำระเงินสำเร็จ</h5>
                                    <h5 class="text-white text-bold-400 mb-0">฿ @_amt.ToString("#,0.00")</h5>
                                </div>
                                <div class="p-2 text-center bg-success bg-darken-2 rounded-right">
                                    <i class="icon-check font-large-2 text-white"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-8 mx-auto">
                    <a class="btn btn-outline-secondary" asp-action="Index" asp-controller="CheckOut" asp-route-customer="@_cus"><i class="la la-arrow-left"></i> Back to Check Out</a>
                </div>
            }
            else if (ViewBag.R == "W")
            {
                <div class="col-12">
                    <h2 class="text-center"> Please Wait .. โปรดรอสักครู่ </h2>
                    <div class="loader-wrapper">
                        <div class="loader-container">
                            <div class="ball-rotate loader-info">
                                <div></div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="col-12">
                    <div class="card">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="p-2 bg-gradient-x-danger text-white media-body text-left rounded-left">
                                    <h5 class="text-white">เกิดข้อผิดพลาดในการชำระเงิน : @Html.Raw(ViewBag.R)</h5>
                                    <h5 class="text-white text-bold-400 mb-0">฿ @_amt.ToString("#,0.00")</h5>
                                </div>
                                <div class="p-2 text-center bg-danger bg-darken-2 rounded-right">
                                    <i class="icon-close font-large-2 text-white"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
</div>

@section Scripts {

<script>



    $(function () {
        var url_string = window.location.href;
        var url = new URL(url_string);
        var _amt = url.searchParams.get("AMT");
        var _ret = url.searchParams.get("ret");
    })
</script>

}

ForntEnd/FrontEnd.Web/FrontEnd.Web/Views/CheckOut/Review.cshtml
@model InvoiceData
<div class="content-body">
    <!-- Bootstrap Checkout form -->
    <section id="social-cards">

        <div class="row mt-2">
            <div class="col-md-5 order-md-2">

                <div class="card overflow-hidden">
                    <div class="card-content">
                        <div class="media align-items-stretch">

                            <div class="media-body p-2">
                                <h4>ยอดชำระ</h4>
                                <span></span>
                            </div>
                            <div class="media-right p-2 media-middle">
                                <h1 class="info">@Model.InvoiceAmount.ToString("#,0.00")</h1>
                            </div>
                            <div class="bg-info p-2 media-middle">
                                <i class="icon-credit-card font-large-2 text-white"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-7 order-md-1">
                <div class="needs-validation p-2 bg-white card" novalidate="">

                    <div class="row">
                        <div class="col-5 mb-1">
                            <label for="address2">รหัสลูกค้า</label>
                            <input type="text" class="form-control" asp-for="CustomerNo" disabled>
                        </div>
                        <div class="col-7 mb-1">
                            <label for="address2">ชื่อลูกค้า</label>
                            <input type="text" class="form-control" asp-for="CustomerName" disabled>
                        </div>
                        <div class="mb-1 col-5">
                            <label for="address2">ใบแจ้งหนี้เลขที่</label>
                            <input type="text" class="form-control" asp-for="InvoiceNo" disabled>
                        </div>

                        <div class="mb-1 col-7">
                            <label for="address2"> โทรศัพท์ </label>
                            <input type="text" class="form-control" asp-for="Telephone" disabled>
                        </div>
                        <div class="mb-1 col-7">
                            <label for="address2">อีเมล์</label>
                            <input type="text" class="form-control" asp-for="Email" disabled>
                        </div>

                        <div class="mb-1 col-5  pt-2 text-right">
                            <form method="post" asp-action="ProcessCheckOut" asp-controller="CheckOut">
                                <input type="hidden" id="local_amount" name="local_amount" value="@Model.InvoiceAmount.ToString("#.00")" />
                                <input type="hidden" id="local_invoice" name="local_invoice" value="@Model.InvoiceNo" />
        <input type="hidden" id="local_custno" name="local_custno" value="@Model.CustomerNo" />
        <input type="hidden" id="local_custname" name="local_custname" value="@Model.CustomerName" />
                                <input type="hidden" id="local_tel" name="local_tel" value="@Model.Telephone" />
                                <input type="hidden" id="local_email" name="local_email" value="@Model.Email" />
                                <script type="text/javascript"
                                        src="https://kpaymentgateway.kasikornbank.com/ui/v2/kpayment.min.js"
                                        data-apikey="pkey_prod_1125XOVjv6Kw8oMmxo07xUfP8LwLXI8jUCbY"
                                        data-amount="@Model.InvoiceAmount.ToString("#.00")"
                                        data-payment-methods="card"
                                        data-name="ILINK"
                                        data-mid="451005589392001">
                                </script>
                            </form>
                        </div>

                    </div>                 
                </div>
            </div>
        </div>
    </section>
    <!-- // Bootstrap Checkout form end -->

</div>
@section Scripts {

    <script>
        $(function () {
            $(".pay-button").addClass("btn btn-lg btn-block btn-info  btn-glow text-white w-100");
        });
    </script>

}